### ISSUE TITLE
Init: TODO list

### ISSUE THREAD

**Issue by klardotsh** [dockwa/seatrial#1]
- [x] man + html doc pages (#10)
- [ ] docker (#10) + homebrew (dockwa/homebrew-public#1) packaging
- [ ] Backing implementations for `PipelineAction`:
    - [x] `Combinator` (#5)
        - [x] `AllOf` (#5)
        - [x] `AnyOf` (#5)
        - [x] `NoneOf` (#5)
    - [x] `ControlFlow`
        -  [x] `GoTo`
    - [ ] HTTP stuff
        - [x] Basic verb dispatch
        - [x] Basic inline header dispatch
            - [x] Plaintext
            - [x] Lua Reference
        - [ ] Merge headers with the global ones from the Persona
        - [x] Basic query param dispatch
            - [x] Plaintext
            - [x] Lua Reference
        - [x] Request bodies (POST, PUT, etc.) (#7)
    - [x] `Validator` (#5)
        - [x] `AssertHeaderExists` (#5)
        - [x] `AssertStatusCode` (#5)
        - [x] `AssertStatusCodeInRange` (#5)
        - [x] `WarnUnlessHeaderExists` (#5)
        - [x] `WarnUnlessStatusCode` (#5)
        - [x] `WarnUnlessStatusCodeInRange` (#5)
        - [x] `LuaFunction` (#5)
